### ISSUE TITLE
What license for the Daily Puzzle artwork and code?

### ISSUE THREAD

**Issue by daniel-thompson** [sh1ura/daily-puzzle-and-its-solver#1]
Hello

This looks like a great puzzle and will probably get one built on my laser cutter so I can play with it.

Can you tell me your approach to licensing the artwork and code in this repo?

For example if you added an open source or creative commons license to cover the repo then it becomes possible for others who make new things derived from this repo to share them. With no license in the github repo I think any derived works will perhaps stay secret?

Daniel.

**Comment by sh1ura** [comment]
Hi Daniel,

Thanks for your kind advice. I would like to make this repo as CC-BY-NC-SA.
Actually same puzzle was made public in instructables and Thingiverse under
CC-BY-NC-SA license,

rectangular version
https://www.thingiverse.com/thing:5322744
https://www.instructables.com/Daily-Puzzle/

hexagonal version
https://www.thingiverse.com/thing:5325527
https://www.instructables.com/Daily-Hexagonal-Puzzle/

I am not good at github -- I just added a LICENSE file but I am not sure if it is ok or not.

**Comment by daniel-thompson** [comment]
> I am not good at github -- I just added a LICENSE file but I am not sure if it is ok or not.

That's absolutely fine. I quite often include a licensing summary in the README too (https://github.com/daniel-thompson/laser-lab for example) but that only to be extra helpful. I think people can get everything they need from the license file.
